<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <RootNamespace>GryOnlineMetadata</RootNamespace>
    <AssemblyName>GryOnlineMetadata</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="PlayniteSDK" Version="6.17.0" />
    <Reference Include="System.Web.Extensions" />
    <Reference Include="PresentationFramework" />
    <Reference Include="PresentationCore" />
    <Reference Include="WindowsBase" />
    <Reference Include="System.Xaml" />
  </ItemGroup>
  <ItemGroup>
    <None Include="extension.yaml" CopyToOutputDirectory="Always" />
    <None Include="icon.png" CopyToOutputDirectory="Always" />
  </ItemGroup>
</Project>
